version: '3.3'

volumes:
  pg_data:
  static:
  backend_static:
  backend_media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: dordzh99/foodgram_backend
    env_file: .env
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      - db

  frontend:
    image: dordzh99/foodgram_frontend
    env_file: .env
    volumes:
      - static:/app/result_build/build
    depends_on:
      - db

  nginx:
    image: dordzh99/foodgram_gateway
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
    depends_on:
      - backend
      - frontend
